branch-defaults:
  master:
    environment: Fitter-env
environment-defaults:
  Fitter-env:
    branch: null
    repository: null
  fittingcal:
    branch: null
    repository: null
global:
  application_name: Fitter
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.5.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
