# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='FREE', max_length=4)),
                ('bot_length', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('hip', models.FloatField(default=0)),
                ('crotch', models.FloatField(default=0)),
                ('thigh', models.FloatField(default=0)),
                ('hem', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('man', '남자'), ('woman', '여자')], default='woman', max_length=5)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('shoulder_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('chest_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('sleeve_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('waist_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('hip_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('crotch_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('length_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('thigh_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('hem_a', models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SameClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_nick', models.CharField(default='Untitled', max_length=80)),
                ('same_photo', django_resized.forms.ResizedImageField(blank=True, upload_to='%Y/%m/%d')),
                ('same_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SingleDataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_size', models.CharField(default='{}', max_length=250)),
                ('single_person_dict', models.CharField(default='{}', max_length=250)),
                ('clothes_dict', models.CharField(default='{}', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('man', '남자'), ('woman', '여자')], default='woman', max_length=5)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('shoulder', models.CharField(default=None, max_length=30)),
                ('chest', models.CharField(default=None, max_length=30)),
                ('arm', models.CharField(default=None, max_length=30)),
                ('waist', models.CharField(default=None, max_length=30)),
                ('bottom_waist', models.CharField(default=None, max_length=30)),
                ('crotch', models.CharField(default=None, max_length=30)),
                ('thigh', models.CharField(default=None, max_length=30)),
                ('length', models.CharField(default=None, max_length=30)),
                ('hem', models.CharField(default=None, max_length=30)),
                ('hip', models.CharField(default=None, max_length=30)),
                ('crotch_height', models.CharField(default=None, max_length=30)),
                ('middle_thigh', models.CharField(default=None, max_length=30)),
                ('knee', models.CharField(default=None, max_length=30)),
                ('calf', models.CharField(default=None, max_length=30)),
                ('nipple', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TopClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='FREE', max_length=4)),
                ('top_length', models.FloatField(default=0)),
                ('shoulder', models.FloatField(default=0)),
                ('chest', models.FloatField(default=0)),
                ('sleeve', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_nick_set', to='fitterKakao.SameClothes')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_photo_set', to='fitterKakao.SameClothes')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_url_set', to='fitterKakao.SameClothes')),
            ],
        ),
        migrations.AddField(
            model_name='bottomclothes',
            name='nick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_nick_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AddField(
            model_name='bottomclothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_photo_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AddField(
            model_name='bottomclothes',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_url_set', to='fitterKakao.SameClothes'),
        ),
    ]
