# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeinfo',
            name='arm',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='bottom_waist',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='calf',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='chest',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='crotch',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='crotch_height',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='hem',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='hip',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='knee',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='length',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='middle_thigh',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='nipple',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='shoulder',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='thigh',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sizeinfo',
            name='waist',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
