# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0003_criteriabottom_criteriatop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sameclothes',
            name='same_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
