# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0004_auto_20171202_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sameclothes',
            name='same_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
