# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0007_auto_20170607_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.FloatField(default=0)),
                ('bot_length', models.FloatField(default=0)),
                ('crotch', models.FloatField(default=0)),
                ('thigh', models.FloatField(default=0)),
                ('hem', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='topclothes',
            old_name='length',
            new_name='top_length',
        ),
        migrations.AddField(
            model_name='person',
            name='crotch_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='hem_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='hip_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='length_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='thigh_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
    ]
