# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0009_auto_20170608_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=10),
        ),
        migrations.AddField(
            model_name='bottomclothes',
            name='size',
            field=models.CharField(default='FREE', max_length=4),
        ),
        migrations.AddField(
            model_name='topclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=10),
        ),
        migrations.AddField(
            model_name='topclothes',
            name='size',
            field=models.CharField(default='FREE', max_length=4),
        ),
    ]
