# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0010_auto_20170613_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='waist_a',
            field=models.IntegerField(choices=[(0, '많이 남는다'), (1, '별로 불편한 것이 없다'), (2, '낀다')], default=1),
        ),
        migrations.AlterField(
            model_name='bottomclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=20),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=20),
        ),
    ]
