# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0011_auto_20170617_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('man', '남자'), ('woman', '여자')], default='woman', max_length=5),
        ),
    ]
