# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0013_auto_20170709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
