# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0014_auto_20170709_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomclothes',
            name='hip',
            field=models.FloatField(default=0),
        ),
    ]
