# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0015_bottomclothes_hip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('man', '남자'), ('woman', '여자')], default='woman', max_length=5)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('shoulder', models.CharField(default=None, max_length=30)),
                ('chest', models.CharField(default=None, max_length=30)),
                ('arm', models.CharField(default=None, max_length=30)),
                ('waist', models.CharField(default=None, max_length=30)),
                ('bottom_waist', models.CharField(default=None, max_length=30)),
                ('crotch', models.CharField(default=None, max_length=30)),
                ('thigh', models.CharField(default=None, max_length=30)),
                ('length', models.CharField(default=None, max_length=30)),
                ('hem', models.CharField(default=None, max_length=30)),
                ('hip', models.CharField(default=None, max_length=30)),
                ('crotch_height', models.CharField(default=None, max_length=30)),
                ('middle_thigh', models.CharField(default=None, max_length=30)),
                ('knee', models.CharField(default=None, max_length=30)),
                ('calf', models.CharField(default=None, max_length=30)),
                ('nipple', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
