# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0016_sizeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topclothes',
            name='nick',
            field=models.CharField(default='Untitled', error_messages={'required': '채워주세요.'}, max_length=50),
        ),
    ]
