# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0017_auto_20170731_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='topclothes',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='nick',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
