# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0018_auto_20170731_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomclothes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='bot/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='top/%Y/%m/%d'),
        ),
    ]
