# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 07:50
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0021_auto_20170731_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomclothes',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, upload_to='bot/%Y/%m/%d'),
        ),
    ]
