# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0023_auto_20170803_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sameclothes',
            old_name='top_photo',
            new_name='same_photo',
        ),
        migrations.RemoveField(
            model_name='sameclothes',
            name='bot_photo',
        ),
    ]
