# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0024_auto_20170803_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomclothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitterKakao.SameClothes'),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitterKakao.SameClothes'),
        ),
    ]
