# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0025_auto_20170803_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomclothes',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_url_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AddField(
            model_name='sameclothes',
            name='same_nick',
            field=models.CharField(default='무제(Untitled,2017)', max_length=80),
        ),
        migrations.AddField(
            model_name='sameclothes',
            name='same_url',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='topclothes',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_url_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AlterField(
            model_name='bottomclothes',
            name='nick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_nick_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AlterField(
            model_name='bottomclothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomclothes_photo_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AlterField(
            model_name='sameclothes',
            name='same_photo',
            field=django_resized.forms.ResizedImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='nick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_nick_set', to='fitterKakao.SameClothes'),
        ),
        migrations.AlterField(
            model_name='topclothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topclothes_photo_set', to='fitterKakao.SameClothes'),
        ),
    ]
