# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0026_auto_20170804_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleDataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_size', models.CharField(default='{}', max_length=250)),
                ('single_person_dict', models.CharField(default='{}', max_length=250)),
                ('clothes_dict', models.CharField(default='{}', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='chest_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='crotch_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='hem_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='hip_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='length_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='shoulder_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='sleeve_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='thigh_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='waist_a',
            field=models.IntegerField(choices=[(0, '작다'), (1, '보통'), (2, '크다')], default=1),
        ),
        migrations.AlterField(
            model_name='sameclothes',
            name='same_nick',
            field=models.CharField(default='Untitled', max_length=80),
        ),
        migrations.AlterField(
            model_name='sameclothes',
            name='same_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
