# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitterKakao', '0027_auto_20170811_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledatalist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
